## Factors Associated to Work Arrangement Preference

@ruger-2024 show in their study employees may be able to save an average of 14% of their time from commuting. They add that this would increase in the long run. Furthermore, they explain that only high shares of WfH are linked to substantial drops in commuting time, and reductions are larger for women than men. This may be explained by differences in job selection and commuting tolerance, where men with low WFH shares are more likely to accept jobs involving longer commutes if they require fewer days in the office, while women may place relatively higher value on jobs with shorter commuting distances. Overall, when accounting for workers' reported WfH preferences, their results suggest maximum potential future commuting time savings of about 17–25% compared to 2019.

The 2024 Household Income and Labour Dynamics in Australia (HILDA) Survey data shows workforce participation in jobs allowing WfH increased by 9 percentage points for women with children under 4 years old and 4.4 percentage points for people with a disability from 2019 to 2023. It is also observed that prior to the pandemic, carers, those with limiting condition, and women with children are among those with the highest WfH rates. With the onset of the pandemic until 2023, rate differences between the former group and general workers, as well as women without children decreased, making WfH rates more similar across groups (@ceda-2024). This suggests that even before the pandemic, the former group had a higher tendency toward WfH. As @barrero-2022 states, married persons—both men and women who are also carers---tend to place more value on the WfH option when they have children aged 14 years or younger.

In their study, @vij-2023 shows that an average worker would be willing to forego around 4 to 8 percent of their annual wages in exchange of an ability to WfH on some workdays and/or workhours. In terms age, workers in their 20's have the lowest WfH valuation and this is opposite to those in their 30's and 50's. They explain that this is associated to younger workers being at the start of their career and therefore tending to seek direct interaction with colleagues and guidance from supervisors. They also find that more educated workers are more willing to accept a pay cut for an ability to WfH as their jobs require a greater capability of being done remotely. Women also tend to value the flexibility of WfH more than men do, a pattern often attributed in the literature to their greater caregiving and household responsibilities (e.g. Wiswall and Zafar, 2017). In terms of household structure, people who live alone have the smallest compensating wage differential, indicating that only a small wage premium is required for them to accept working in the office. In contrast, couples with children living at home are willing to forgo the largest share of their salary in exchange for the option to work from home.

The DITRDCSA defines *"WfH uptake as the the proportion of job tasks and activities that were done remotely at a given point in time"*. It is further noted that *"individuals are considered to have WfH capability if they could have done their job remotely on some days in a week if appropriate company policies and resources for remote working were put in place"*. Undeniably, WfH capability differs based on the occupation of the individual. As to the report, WfH capability and uptake are much higher for managerial employees than non-managerial employees. @beck-2021 finds that during the pandemic, those with white collar occupations report to WfH for an average of 4.2 days compared to 1.5 for blue collar. The nature of job also interacts with gender. As previously mentioned, WfH uptake is higher in females than males. Aside from conventional roles, the Australian Bureau of Statistics (2016a) demonstrates that 26% of females while 15% of males worked as Professionals; 22% compared to 6% of males worked as clerical and administrative workers. @vij-2023 show the mentioned occupations to have the highest WfH uptake during the pandemic.

The DITRDCSA divides respondents (nonmanagerial and managerial employees who did not change their job during the pandemic) according to whether their location is a capital or a regional city. The eight regional cities is composed of Sydney, Melbourne, Adelaide, Perth, Brisbane, Canberra, Darwin and Hobart while Gold Coast-Tweed Heads, Newcastle-Maitland, Central Coast, Sunshine Coast, Wollongong, Geelong, Townsville, Cairns or Toowoomba make up the regional cities. They show that WfH capability and uptake are higher for the capital cities than the regional cities and this significant gap remains evident through early 2021. Among the non-managerial employees, WfH uptake and capability are higher in Central Business Districts (the five big capital cities) as well as in inner BCARR rings compared to their counterparts.