## Data source

```{r}
library(dplyr)
library(tidyr)
```


```{r}
raw <- read.csv("data/Replication file/Data/G-SWA.csv") %>% 
  filter(country == 'Australia 2') %>% 
  dplyr::select(c(regionname,
                  gender,
                  age, #agegroups,
                  education,
                  industry_job,
                  married,
                  with_kids,
                  daysemployer_work_home,
                  daysemployee_work_home,
                  value_WFH_rawpercent25,
                  commuting_time, # * commute_time_hs
                  WFHperceptions,
                  ever_WFH,
                  return_office
                  )) %>%
  dplyr::select(-c(daysemployer_work_home)) %>%
  mutate(decision = ifelse(return_office == 'Comply and return to worksite', 1, 0))
```


```{r include = FALSE, eval = FALSE}
raw %>% pull(ever_WFH) %>% table()# %>% 
  #filter(if_any(everything(), is.na))# %>% pull(return_office) #%>% table()
```


```{r include = FALSE, eval = FALSE}
raw$with_kids
```


```{r include = FALSE}
raw %>% group_by(decision) %>% summarise(mean(with_kids, na.rm = TRUE))
```


```{r include = FALSE, eval = FALSE}
cols_to_check <- c("regionname", "gender", "age", "education", "industry_job", 
                   "married", "with_kids",
                   "daysemployee_work_home", "value_WFH_rawpercent25", 
                   "commuting_time", "WFHperceptions")

# Replace 'target_variable' with your outcome column
lapply(raw[cols_to_check], function(x) table(x, raw$decision, useNA = "ifany"))

```

```{r include = FALSE, eval = FALSE}
setdiff(cols_to_check, names(raw))

```


```{r include = FALSE, eval = FALSE}
raw %>% 
  group_by(regionname, gender, agegroups, education, industry_job, married, with_kids) %>%
  summarise(n = n(), .groups = "drop") %>%
  mutate(prop = n / sum(n))

```


https://wfhresearch.com/wp-content/uploads/2022/10/Working-from-Home-Around-the-World-16-October-2022.pdf
